apply plugin: 'com.android.library'

android {
    namespace 'com.memoanchor.nativesplash'
    compileSdk 36
    buildToolsVersion = "36.0.0"

    defaultConfig {
        minSdk 25
        targetSdk 36
    }

    lint {
        abortOnError false
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            res.srcDirs = ['res']
        }
    }
}
